//
// Created by Yifei Yao on 7/31/23.
//

#ifndef CS3113_GAME_PROGRAMMING_PLATFORMER_UTILITY_H_
#define CS3113_GAME_PROGRAMMING_PLATFORMER_UTILITY_H_

class Utility {

};

#endif //CS3113_GAME_PROGRAMMING_PLATFORMER_UTILITY_H_
